### ISSUE TITLE
重构

### ISSUE THREAD

**Issue by itdebug** [ZevenFang/zevencourse#6]
我发现你这个项目写的挺好的 所以特地将项目重构为SpringBoot项目 
重构后的地址: https://github.com/sayByeTheory/xk 
如果有什么疑问, 可以联系我下 qq: 2537074899

**Comment by ZevenFang** [comment]
谢谢，这个项目是我大二的课程设计，也有好长一段时间没有更新维护了，前端还是用 gulp 做的构建工具，我会把你的项目地址放到 Readme
